name: Build-Deploy

on:
  pull_request:
  push:

jobs:	
  build:	
    runs-on: ubuntu-latest
    steps:	
    - uses: actions/checkout@v3	
    - name: Setup .NET	
      uses: actions/setup-dotnet@v2	
      with:	
        dotnet-version: 6.0.x	
    - name: Restore dependencies	
      run: dotnet restore	
    - name: Build	
      run: dotnet build --no-restore	
    - name: Test	
      run: dotnet test --no-build --verbosity normal 
    - name: Publish
      run: dotnet publish src/RazorApp.csproj -c Release -o release -r osx-x64 --self-contained
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: deploy
        path: /home/runner/work/dotnetPractice/dotnetPractice/release/

  dev:
    name: Deploy to development
    environment:
      name: development
    runs-on: self-hosted
    needs: build

    steps:
    - name: Download Deploy
      uses: actions/download-artifact@v2
      with:
        name: deploy
    - name: Install dependencies
      run: |
        dotnet restore
        dotnet build

    - name: Kill old process
      run: |
        if [[ 2 -ne 3 ]]; then                                                                                                                                                             130 ↵
        echo "This should print"
        fi
      
    - name: Deploy to dev
      run: |
        RUNNER_TRACKING_ID="" && RazorApp &
        echo "$!" > "$HOME/dotnet_old_pid"
