name: Build-Deploy

on:
  push:
  pull_request:

jobs:	
  build:	
    runs-on: ubuntu-latest
    steps:	
    - uses: actions/checkout@v3	
    - name: Setup .NET	
      uses: actions/setup-dotnet@v2	
      with:	
        dotnet-version: 6.0.x	
    - name: Restore dependencies	
      run: dotnet restore	
    - name: Build	
      run: dotnet build --no-restore	
    - name: Test	
      run: dotnet test --no-build --verbosity normal 
    - name: Publish
      run: dotnet publish src/RazorApp.csproj -c Release -o release
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: deploy
        path: /home/runner/work/dotnetPractice/dotnetPractice/release/

  dev:
    name: Deploy to Dev
    environment:
      name: dev
    runs-on: self-hosted
    needs: build

    steps:
    - name: Download Deploy
      uses: actions/download-artifact@v2
      with:
        name: deploy