name: Build-Deploy

on:
  pull_request:
  push:

jobs:	
  build:	
    runs-on: ubuntu-latest
    steps:	
    - uses: actions/checkout@v3	
    - name: Setup .NET	
      uses: actions/setup-dotnet@v2	
      with:	
        dotnet-version: 6.0.x	
    - name: Restore dependencies	
      run: dotnet restore	
    - name: Build	
      run: dotnet build --no-restore	
    - name: Test	
      run: dotnet test --no-build --verbosity normal 
    - name: Publish
      run: dotnet publish src/RazorApp.csproj -c Release -o release
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: deploy
        path: /home/runner/work/dotnetPractice/dotnetPractice/release/

  dev:
    name: Deploy to development
    environment:
      name: development
    runs-on: self-hosted
    needs: build

    steps:
    - name: Download Deploy
      uses: actions/download-artifact@v2
      with:
        name: deploy
    - name: Deploy to dev
      run: dotnet /Users/sthomas/Learning/Runners/actions-runner/_work/dotnetPractice/dotnetPractice/RazorApp.dll

  prod:
    name: Deploy to production
    environment:
      name: production
    runs-on: self-hosted
    needs: dev

    steps:
    - name: Download Deploy
      uses: actions/download-artifact@v2
      with:
        name: deploy
    - name: Deploy to dev
      run: dotnet /Users/sthomas/Learning/Runners/actions-runner/_work/dotnetPractice/dotnetPractice/RazorApp.dll &
    - name: Keep Open for 5 minutes
      run: sleep 300
    - name: Announce closure
      run: echo "Exiting prod"